spring.application.name=agent
langchain4j.anthropic.chat-model.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=gpt-4o
langchain4j.anthropic.chat-model.log-requests=true
langchain4j.anthropic.chat-model.log-responses=true
