spring.application.name=agent
langchain4j.anthropic.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-haiku-4-5-20251001
langchain4j.anthropic.chat-model.log-requests=true
langchain4j.anthropic.chat-model.log-responses=true

ethereum.rpc.url=${ALCHEMY_NODE_URL}
axl.base.url=http://127.0.0.1:9002