agent.role=guard
agent.services=protection
agent.personality=brave,naive

server.port=8082
axl.base.url=http://127.0.0.1:9013
axl.peerId=1f093ae35aa45dd40c7860b7c6edccade797f18db5fde810caabbe29aacef0f3

wallet.address=0x44cb0a01c5e3aa65d542a863e57a06d8dd85214d

catalog.items.protection=0.001

agent.motivation.stock.hunger=1
agent.motivation.threshold.hunger=10