spring.application.name=p2p-agent-sim
langchain4j.anthropic.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-haiku-4-5-20251001
langchain4j.anthropic.chat-model.log-requests=true
langchain4j.anthropic.chat-model.log-responses=true

ethereum.rpc.url=${ALCHEMY_NODE_URL}